### ISSUE TITLE
Error since update to latest version

### ISSUE THREAD

**Issue by janicduplessis** [vvo/selenium-standalone#113]
I updated from verison 4.4.2 and I get this error. I reverted back and now it works fine. It seems to try to download the IE driver even if I don't have it in my config. I'm using Node v. 0.12.2 on Windows.

Error:

[Error: Could not request headers from http://selenium-release.storage.googleapi
s.com/2.45/IEDriverServer_x64_2.46.0.zip: ]
{ [Error: [quit()] connect ECONNREFUSED]
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect' }

Config: 
``` javascript
selenium.install({
	version: '2.45.0',
	baseURL: 'http://selenium-release.storage.googleapis.com'
	drivers: {
		chrome: {
			version: '2.15',
			arch: process.arch,
			baseURL: 'http://chromedriver.storage.googleapis.com'
		},
	}
});
```

**Comment by vvo** [comment]
Try:

```js
selenium.install({
    version: '2.45.0',
    baseURL: 'http://selenium-release.storage.googleapis.com'
    drivers: {
        chrome: {
            version: '2.15',
            arch: process.arch,
            baseURL: 'http://chromedriver.storage.googleapis.com'
        },
        ie: {
          version: '2.45.0',
          arch: process.arch,
          baseURL: 'http://selenium-release.storage.googleapis.com'
       }
    }
});
```

**Comment by vvo** [comment]
I think the computation for the IE url is based on the main selenium version you give, thus we try to get 2.45/2.46.zip, which does not exists.

Maybe submit a PR to fix this? :)

**Comment by janicduplessis** [comment]
Yeah sure, I'll take a look at it.

**Comment by janicduplessis** [comment]
I haven't found a clean way to fix this. The IE driver version seems really dependent on the selenium version. If I fixed the download URL for the IE driver I got another error because the IE driver could not find 2.46.0-server.jar. The only solution I see is to use the selenium version to download the IE driver but then the drivers -> ie -> version config would be completely ignored.

In the meantime, I just bumbed my selenium version to 2.46 and specified a ie version so it doesn't happen again.

**Comment by Junikorn** [comment]
Guys, the issue still persists, are there any fixes planned or do I have to fix this manually? (the issue affects other libraries that depend on yours so it's hard to fix in my project)

```
Starting Selenium server for local browsers
selenium-standalone installation starting
selenium install:
from: http://selenium-release.storage.googleapis.com/2.47/selenium-server-standalone-2.47.1.jar
to: C:\Playground\Polymer\node_modules\web-component-tester\node_modules\wct-local\node_modules\selenium-standalone\.selenium\selenium-server\2.47.1-server.jar

chrome install:
from: http://chromedriver.storage.googleapis.com/2.16/chromedriver_win32.zip
to: C:\Playground\Polymer\node_modules\web-component-tester\node_modules\wct-local\node_modules\selenium-standalone\.selenium\chromedriver\2.16-x64-chromedriver
---
ie install:
from: http://selenium-release.storage.googleapis.com/2.47/IEDriverServer_x64_2.46.0.zip
to: C:\Playground\Polymer\node_modules\web-component-tester\node_modules\wct-local\node_modules\selenium-standalone\.selenium\iedriver\2.46.0-x64-IEDriverServer.exe
---
File from http://chromedriver.storage.googleapis.com/2.16/chromedriver_win32.zip has already been downloaded
[13:01:01] 'wct:local' errored after 3.3 min
[13:01:01] Error: Could not request headers from http://selenium-release.storage.googleapis.com/2.47/IEDriverServer_x64_2.46.0.zip:
```

**Comment by vvo** [comment]
No one seem to be working on a fix so contribution welcomed
